# Generated by Django 5.2.7 on 2025-10-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercial',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail generado del video (frame a los 2 segundos)', null=True, upload_to='thumbnails/'),
        ),
    ]
