# Generated by Django 5.2.7 on 2025-10-15 22:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comercial_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, help_text='Título descriptivo del link compartido', max_length=255)),
                ('password', models.CharField(blank=True, help_text='Password opcional para acceder', max_length=128, null=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Fecha de expiración del link', null=True)),
                ('permitir_descarga', models.BooleanField(default=True, help_text='Permitir descargar el video')),
                ('activo', models.BooleanField(default=True, help_text='Link activo o deshabilitado')),
                ('vistas', models.IntegerField(default=0, help_text='Número de veces que se ha visto')),
                ('reproducciones', models.IntegerField(default=0, help_text='Número de veces que se ha reproducido')),
                ('ultima_visita', models.DateTimeField(blank=True, help_text='Última vez que se accedió al link', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to='core.comercial')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
