# Generated by Django 5.2.7 on 2025-10-15 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sharedlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del directorio/folder', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Directorio padre (para estructura jerárquica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdirectorios', to='core.directorio')),
                ('repositorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directorios', to='core.repositorio')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'repositorio', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='comercial',
            name='directorio',
            field=models.ForeignKey(blank=True, help_text='Directorio/folder donde está ubicado el comercial', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comerciales', to='core.directorio'),
        ),
    ]
