# Generated by Django 5.2.7 on 2025-10-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_directorio_comercial_directorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercial',
            name='pizarra_thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail de pizarra (frame a 00:02) para vista de edición', null=True, upload_to='pizarra/'),
        ),
        migrations.AlterField(
            model_name='comercial',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail principal (frame a 02:03) para mostrar en el frontend', null=True, upload_to='thumbnails/'),
        ),
    ]
