# Generated by Django 5.2.7 on 2025-10-16 01:19

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comercial_pizarra_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercial',
            name='nombre_original',
            field=models.CharField(blank=True, help_text='Nombre original del archivo subido', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='comercial',
            name='archivo_original',
            field=models.FileField(blank=True, help_text='Archivo master original subido por el usuario.', max_length=512, null=True, upload_to=core.models.upload_to_originals),
        ),
    ]
