# Generated by Django 5.2.7 on 2025-10-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comercial_nombre_original_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nombre_compania',
        ),
        migrations.RemoveField(
            model_name='repositorio',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='customuser',
            name='compania',
            field=models.CharField(blank=True, max_length=255, verbose_name='Compañía'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre Completo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='repositorio',
            name='clave',
            field=models.CharField(blank=True, help_text='Clave manual de 3 caracteres', max_length=3),
        ),
    ]
