# Generated by Django 5.2.7 on 2025-10-16 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_customuser_nombre_compania_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='repositorios',
        ),
        migrations.CreateModel(
            name='RepositorioPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_ver', models.BooleanField(default=True, help_text='Puede ver contenido del repositorio')),
                ('puede_editar', models.BooleanField(default=False, help_text='Puede editar comerciales')),
                ('puede_borrar', models.BooleanField(default=False, help_text='Puede borrar comerciales')),
                ('repositorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_usuario', to='core.repositorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_repositorio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de Repositorio',
                'verbose_name_plural': 'Permisos de Repositorio',
                'unique_together': {('usuario', 'repositorio')},
            },
        ),
    ]
