# Generated by Django 5.2.7 on 2025-10-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_customuser_repositorios_repositoriopermiso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del módulo', max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('storage', 'Storage - Sin restricciones'), ('reel', 'Reel - Solo H.264'), ('broadcast', 'Broadcast - Solo Masters'), ('audio', 'Audio - Solo Audio'), ('images', 'Images - Solo Imágenes')], help_text='Tipo de módulo', max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del módulo y sus restricciones')),
                ('formatos_permitidos', models.JSONField(blank=True, default=list, help_text="Lista de extensiones permitidas (ej: ['.mp4', '.mov'])")),
                ('activo', models.BooleanField(default=True, help_text='Módulo activo')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='repositorio',
            name='modulos',
            field=models.ManyToManyField(blank=True, help_text='Módulos asignados a este repositorio', related_name='repositorios', to='core.modulo'),
        ),
    ]
