# Generated by Django 5.2.7 on 2025-10-16 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_modulo_repositorio_modulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercial',
            name='modulo',
            field=models.ForeignKey(blank=True, help_text='Módulo al que pertenece este archivo (Storage, Reel, Broadcast, Audio, Images)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comerciales', to='core.modulo'),
        ),
    ]
