# Generated by Django 5.2.7 on 2025-10-16 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_comercial_modulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='ID único del perfil (ej: admin, operador, cliente)', max_length=50, unique=True, verbose_name='Clave del Perfil')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Perfil')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#5fbf00', help_text='Color en hexadecimal (ej: #5fbf00)', max_length=7)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('puede_acceder_administracion', models.BooleanField(default=False, verbose_name='Acceder a Administración')),
                ('puede_gestionar_repositorios', models.BooleanField(default=False, verbose_name='Gestionar Repositorios')),
                ('puede_gestionar_usuarios', models.BooleanField(default=False, verbose_name='Gestionar Usuarios')),
                ('puede_gestionar_configuracion', models.BooleanField(default=False, verbose_name='Gestionar Configuración')),
                ('puede_crear_directorio', models.BooleanField(default=False, verbose_name='Crear Directorios')),
                ('puede_actualizar_directorio', models.BooleanField(default=False, verbose_name='Actualizar Directorios')),
                ('puede_borrar_directorio', models.BooleanField(default=False, verbose_name='Borrar Directorios')),
                ('puede_subir_archivo', models.BooleanField(default=False, verbose_name='Subir Archivos')),
                ('puede_actualizar_archivo', models.BooleanField(default=False, verbose_name='Actualizar Archivos')),
                ('puede_borrar_archivo', models.BooleanField(default=False, verbose_name='Borrar Archivos')),
                ('puede_descargar', models.BooleanField(default=True, verbose_name='Descargar Archivos')),
                ('puede_mover_archivos', models.BooleanField(default=False, verbose_name='Mover Archivos')),
                ('puede_compartir', models.BooleanField(default=False, verbose_name='Compartir con Privilegios')),
                ('puede_comentar', models.BooleanField(default=False, verbose_name='Comentar')),
                ('puede_guardar_coleccion', models.BooleanField(default=False, verbose_name='Guardar Colecciones')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.perfil', verbose_name='Perfil/Rol'),
        ),
    ]
