# Generated by Django 5.2.7 on 2025-10-16 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_perfil_customuser_perfil'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='directorio',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='directorio',
            name='modulo',
            field=models.ForeignKey(blank=True, help_text='Módulo al que pertenece este directorio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directorios', to='core.modulo'),
        ),
        migrations.AlterUniqueTogether(
            name='directorio',
            unique_together={('nombre', 'repositorio', 'modulo', 'parent')},
        ),
    ]
