# Generated by Django 5.2.7 on 2025-10-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_directorio_unique_together_directorio_modulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercial',
            name='ruta_h264',
            field=models.CharField(blank=True, help_text='Ruta al archivo H.264 transcodificado.', max_length=1024, null=True),
        ),
    ]
