# Generated by Django 5.2.7 on 2025-10-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_comercial_ruta_h264'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercial',
            name='encoded_files',
            field=models.JSONField(blank=True, default=list, help_text='Lista de archivos codificados personalizados con sus metadatos'),
        ),
    ]
