# Generated by Django 5.2.7 on 2025-10-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_comercial_to_broadcast'),
    ]

    operations = [
        # Check if the column exists before renaming
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name='core_sharedlink' 
                        AND column_name='comercial_id'
                    ) THEN
                        ALTER TABLE core_sharedlink 
                        RENAME COLUMN comercial_id TO broadcast_id;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
