# Generated by Django 5.2.7 on 2025-10-20 23:18

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_folio_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id_usr',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='id_mod',
        ),
        migrations.RemoveField(
            model_name='repositorio',
            name='id_repo',
        ),
        migrations.AddField(
            model_name='broadcast',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró/subió el broadcast', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='archivo_original',
            field=models.FileField(blank=True, help_text='Original master file uploaded by user', max_length=512, null=True, upload_to=core.models.upload_to_originals),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='directorio',
            field=models.ForeignKey(blank=True, help_text='Directory/folder where the broadcast is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='core.directorio'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='encoded_files',
            field=models.JSONField(blank=True, default=list, help_text='List of custom encoded files with their metadata'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='estado_transcodificacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pending'), ('PROCESANDO', 'Processing'), ('COMPLETADO', 'Completed'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='modulo',
            field=models.ForeignKey(blank=True, help_text='Module this file belongs to (Storage, Reel, Broadcast, Audio, Images)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='core.modulo'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='nombre_original',
            field=models.CharField(blank=True, help_text='Original filename uploaded', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='pizarra',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible broadcast metadata (product, version, etc.)'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='pizarra_thumbnail',
            field=models.ImageField(blank=True, help_text='Slate thumbnail (frame at 00:02) for edit view', null=True, upload_to='pizarra/'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='repositorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='core.repositorio'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='ruta_h264',
            field=models.CharField(blank=True, help_text='Path to transcoded H.264 file', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='ruta_proxy',
            field=models.CharField(blank=True, help_text='Path to transcoded H.265 proxy file', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Main thumbnail (frame at 07:03) to display in frontend', null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='repositoriopermiso',
            name='puede_borrar',
            field=models.BooleanField(default=False, help_text='Can delete broadcasts'),
        ),
        migrations.AlterField(
            model_name='repositoriopermiso',
            name='puede_editar',
            field=models.BooleanField(default=False, help_text='Can edit broadcasts'),
        ),
        migrations.AlterField(
            model_name='repositoriopermiso',
            name='puede_ver',
            field=models.BooleanField(default=True, help_text='Can view repository content'),
        ),
        migrations.AlterField(
            model_name='sharedlink',
            name='activo',
            field=models.BooleanField(default=True, help_text='Link active or disabled'),
        ),
        migrations.AlterField(
            model_name='sharedlink',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, help_text='Link expiration date', null=True),
        ),
        migrations.AlterField(
            model_name='sharedlink',
            name='password',
            field=models.CharField(blank=True, help_text='Optional password to access', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sharedlink',
            name='permitir_descarga',
            field=models.BooleanField(default=True, help_text='Allow video download'),
        ),
        migrations.AlterField(
            model_name='sharedlink',
            name='reproducciones',
            field=models.IntegerField(default=0, help_text='Number of times played'),
        ),
        migrations.AlterField(
            model_name='sharedlink',
            name='titulo',
            field=models.CharField(blank=True, help_text='Descriptive title of the shared link', max_length=255),
        ),
        migrations.AlterField(
            model_name='sharedlink',
            name='ultima_visita',
            field=models.DateTimeField(blank=True, help_text='Last time the link was accessed', null=True),
        ),
        migrations.AlterField(
            model_name='sharedlink',
            name='vistas',
            field=models.IntegerField(default=0, help_text='Number of times viewed'),
        ),
    ]
