# Generated by Django 5.2.7 on 2025-10-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_comercial_sharedlink_broadcast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorio',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Posición/orden del repositorio (numérico)'),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='folio',
            field=models.CharField(help_text='Folio del repositorio (3–5 alfanuméricos, ej: ABCD o A1B2)', max_length=10, unique=True),
        ),
    ]
