# Generated by Django 5.2.7 on 2025-10-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_comercial_sharedlink_broadcast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorio',
            name='clave',
            field=models.CharField(help_text='Clave/Key manual de 3-5 caracteres', max_length=5),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='folio',
            field=models.CharField(help_text='Folio autogenerado del repositorio', max_length=50, unique=True),
        ),
    ]
