# Generated by Django 5.2.7 on 2025-10-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_comercial_sharedlink_broadcast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorio',
            name='clave',
            field=models.CharField(help_text='Clave/Key de exactamente 4 letras mayúsculas (A-Z)', max_length=4),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='folio',
            field=models.CharField(help_text='Folio autogenerado del repositorio (~15-20 caracteres)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Posición/orden del repositorio en el tablero'),
        ),
    ]
