# Generated by Django 5.2.7 on 2025-10-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_customuser_email_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoriopermiso',
            name='modulos_permitidos',
            field=models.ManyToManyField(blank=True, help_text='Módulos habilitados para este usuario en este repositorio', related_name='permisos_repositorio', to='core.modulo'),
        ),
    ]
