# Generated by Django 4.2.25 on 2025-10-28 14:11

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_broadcast_last_error'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedlink',
            old_name='comercial',
            new_name='broadcast',
        ),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo_original', models.FileField(blank=True, help_text='Archivo de imagen original', max_length=512, null=True, upload_to=core.models.upload_to_originals)),
                ('nombre_original', models.CharField(blank=True, help_text='Nombre original del archivo', max_length=512, null=True)),
                ('tipo_archivo', models.CharField(blank=True, help_text='Tipo de archivo (jpg, png, tiff, psd, ai, svg, etc)', max_length=20, null=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail/preview para mostrar en frontend', null=True, upload_to='thumbnails/')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadata flexible (EXIF, tamaño, resolución, etc)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('last_error', models.TextField(blank=True, help_text='Último error de procesamiento', null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que subió la imagen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_creados', to=settings.AUTH_USER_MODEL)),
                ('directorio', models.ForeignKey(blank=True, help_text='Directorio/folder donde está la imagen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='core.directorio')),
                ('modulo', models.ForeignKey(blank=True, help_text='Module this file belongs to (Images)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='core.modulo')),
                ('repositorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.repositorio')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
