# Generated by Django 4.2.25 on 2025-11-08 00:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_comercial_sharedlink_broadcast_imageasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageasset',
            name='imagen_web',
            field=models.ImageField(blank=True, help_text='Versión optimizada JPG para visualización web', null=True, upload_to='support/'),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='archivo_original',
            field=models.FileField(blank=True, help_text='Archivo de imagen original en formato nativo (sources/)', max_length=512, null=True, upload_to=core.models.upload_to_originals),
        ),
    ]
