# Generated by Django 4.2.25 on 2025-11-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_imageasset_imagen_web_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlink',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to='core.imageasset'),
        ),
        migrations.AlterField(
            model_name='sharedlink',
            name='broadcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to='core.broadcast'),
        ),
        migrations.AlterField(
            model_name='sharedlink',
            name='permitir_descarga',
            field=models.BooleanField(default=True, help_text='Allow download'),
        ),
        migrations.AlterField(
            model_name='sharedlink',
            name='reproducciones',
            field=models.IntegerField(default=0, help_text='Number of times played/viewed'),
        ),
    ]
