# Generated by Django 4.2.25 on 2025-11-10 15:03

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_sharedlink_image_alter_sharedlink_broadcast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageasset',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Processing'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='StorageAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo_original', models.FileField(help_text='Original file in any format', max_length=512, upload_to=core.models.upload_to_originals)),
                ('nombre_original', models.CharField(help_text='Original filename', max_length=512)),
                ('tipo_archivo', models.CharField(blank=True, help_text='File extension (pdf, zip, docx, etc)', max_length=50, null=True)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional thumbnail for file preview', null=True, upload_to='thumbnails/')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible metadata (mime type, file info, etc)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pending'), ('PROCESANDO', 'Processing'), ('COMPLETADO', 'Completed'), ('ERROR', 'Error')], default='COMPLETADO', help_text='Processing status', max_length=20)),
                ('last_error', models.TextField(blank=True, help_text='Last processing error if any', null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_files_creados', to=settings.AUTH_USER_MODEL)),
                ('directorio', models.ForeignKey(blank=True, help_text='Directory/folder where the file is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_files', to='core.directorio')),
                ('modulo', models.ForeignKey(blank=True, help_text='Module this file belongs to (Storage)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_files', to='core.modulo')),
                ('repositorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_files', to='core.repositorio')),
            ],
            options={
                'verbose_name': 'Storage File',
                'verbose_name_plural': 'Storage Files',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
