# Generated by Django 4.2.25 on 2025-11-11 03:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_imageasset_estado_storageasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('upload', 'Upload'), ('transcode', 'Transcode Video'), ('encode_custom', 'Custom Encode Video'), ('audio_process', 'Process Audio'), ('audio_encode', 'Encode Audio'), ('image_process', 'Process Image'), ('storage', 'Storage Save'), ('other', 'Other')], default='other', max_length=40)),
                ('file_name', models.CharField(blank=True, help_text='Nombre del archivo involucrado (original)', max_length=512, null=True)),
                ('error_message', models.TextField(help_text='Mensaje de error legible / stderr truncado')),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Metadata adicional contextual (comando, returncode, etc)')),
                ('resolved', models.BooleanField(default=False, help_text='Marcado manualmente como resuelto/corregido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errores', to='core.audio')),
                ('broadcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errores', to='core.broadcast')),
                ('directorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errores_procesamiento', to='core.directorio')),
                ('imagen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errores', to='core.imageasset')),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errores_procesamiento', to='core.modulo')),
                ('repositorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errores_procesamiento', to='core.repositorio')),
                ('storage_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errores', to='core.storageasset')),
            ],
            options={
                'verbose_name': 'Error de Procesamiento',
                'verbose_name_plural': 'Errores de Procesamiento',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['repositorio', 'modulo', 'stage'], name='core_proces_reposit_960793_idx'), models.Index(fields=['fecha_creacion'], name='core_proces_fecha_c_264e95_idx')],
            },
        ),
    ]
