# Generated by Django 4.2.25 on 2025-11-11 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_processingerror'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncodingPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del preset', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del preset y casos de uso')),
                ('categoria', models.CharField(choices=[('broadcast', 'Broadcast'), ('web', 'Web'), ('mobile', 'Mobile'), ('social', 'Social Media'), ('custom', 'Personalizado')], default='custom', max_length=20)),
                ('settings', models.JSONField(help_text='Configuración completa del preset (formato, codec, resolución, etc.)')),
                ('es_global', models.BooleanField(default=False, help_text='Si es global, todos los usuarios pueden verlo. Si no, solo el creador.')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo y disponible para uso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('veces_usado', models.IntegerField(default=0, help_text='Contador de veces que se ha usado este preset')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presets_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preset de Codificación',
                'verbose_name_plural': 'Presets de Codificación',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['categoria', 'activo'], name='core_encodi_categor_e5e7a1_idx'), models.Index(fields=['creado_por', 'activo'], name='core_encodi_creado__868574_idx')],
            },
        ),
    ]
